# Exercises for Numpy

1- Import numpy as `np` and print the version number. 

In [2]:
import numpy as np
print(np._version_)

AttributeError: module 'numpy' has no attribute '_version_'

2- Create a 1D array of numbers from 0 to 9 
- Desired output:
```Python
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [ ]:
arr= np.arange(10) #array + range 
arr

3- Create a 3×3 numpy array of all True’s
- Desired output:
```Python
#> array([[ True,  True,  True],
#>        [ True,  True,  True],
#>        [ True,  True,  True]], dtype=bool)
```

In [20]:
arr1= np.full((3,3),True,dtype=bool)
arr1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4- Extract all odd numbers from `arr` 
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#> array([1, 3, 5, 7, 9])
```

In [36]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_odd= [i for i in arr if i%2!=0]
arr_odd

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5- Replace all odd numbers in arr with -1
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [38]:
arr_1=[-1 if i%2!=0 else i for i in arr ]
arr_1

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

6- Replace all odd numbers in arr with -1 without changing `arr` 
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [41]:
out= arr.copy()
out=[-1 if i%2!=0 else i for i in arr ]
print(out)
print(arr)

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]
[0 1 2 3 4 5 6 7 8 9]


7- Convert a 1D array to a 2D array with 2 rows
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [57]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
output= numpy.reshape(arr, (2,5)) #for reshaping 
output
#output= [[arr[:5],arr[5:]]]
#np.array_split(arr,2)
#in both commands we get the array inside the square brackets 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8- Stack arrays `a` and `b` vertically 
- Input
```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [59]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
result= np.vstack([a,b]) #command to stack vertically
result

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9- Stack the arrays a and b horizontally.
- Input
```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [60]:
result2= np.hstack([a,b]) #command to stack vertically
result2

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10- Get the common items between `a` and `b` 
- Input
```Python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
- Desired output:
```Python
#> array([2, 4])
```

In [62]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c= np.intersect1d(a, b) 
c 
#can you check the results 

array([5])

11- From array `a` remove all items present in array `b` 
- Input
```Python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
- Desired output:
```Python
#> array([1,2,3,4])
```

In [66]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a[~np.in1d(a,b)] #we can also use isin

array([1, 2, 3, 4])

12- Get the positions where elements of `a` and `b` match
- Input
```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```
- Desired output:
```Python
#> (array([1, 3, 5, 7]),)
```

In [71]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b)) #
c= print([i for i, j in enumerate(a) if j in set(b)]) #we keep the index for the equal values 
c

(array([1, 3, 5, 7], dtype=int64),)
[1, 3, 5, 7]


13- Get all items between 5 and 10 from `a`
- Input
```Python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```
- Desired output:
```Python
#> (array([6, 9, 10]),)
```

In [88]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
result = [i for i in a if i>5 if i<=10 ]
np.array(result)

array([ 6,  9, 10])

14- Convert the function `maxx` that works on two scalars, to work on two arrays
- Input
```Python
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
```
```Python
maxx(1, 5)
#> 5
```

- Desired output:

```Python
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [101]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
pair_max = np.vectorize(maxx, otypes=[float]) #to move from scalars to arrays
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

15- Reverse the rows of a 2D array `arr`
- Input
```Python
arr = np.arange(9).reshape(3,3)
```
- Desired output:
```Python
#> array([[6, 7, 8],
#>       [3, 4, 5],
#>       [0, 1, 2]])
```

In [18]:
arr=np.arange(9).reshape(3,3)
print(arr)
np.flip(arr,0) #the numpy.flip(m, axis=None)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

16- Reverse the columns of a 2D array `arr`
- Input
```Python
arr = np.arange(9).reshape(3,3)
```
- Desired output:
```Python
#> array([[6, 7, 8],
#>       [3, 4, 5],
#>       [0, 1, 2]]
```

In [21]:
arr = np.arange(9).reshape(3,3)
print(arr)
np.flip(arr,-1) #Could you please check the results ? 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

17- Create a 2D array of shape 5×3 to contain random decimal numbers between 5 and 10 (use `np.random.seed()` to generate the same random output).
- Desired output: (for seed number equal 10)
```Python
#> array([[6.15037787, 9.68381843, 5.81660184],
#>       [6.33607158, 8.89081653, 9.19812181],
#>       [6.03061665, 5.87761494, 6.72743551],
#>       [7.54088093, 5.13145815, 6.41366737],
#>       [5.77872881, 7.58390137, 5.18263144]])
```

In [135]:
np.random.seed(10)
arr=np.random.uniform(5,10, size=(5,3))
arr


array([[8.85660322, 5.10375975, 8.16824117],
       [8.74401941, 7.49253506, 6.12398323],
       [5.99031432, 8.80265356, 5.84555418],
       [5.44169907, 8.42679909, 9.76696673],
       [5.01974133, 7.56096132, 9.06310481]])

18- Print or show only 3 decimal places of the numpy array `rand_arr`
- Input
```Python
rand_arr = np.random.random((5,3))
```
- Desired output:
```Python
rand_arr[:4]
#> array([[ 0.443,  0.109,  0.97 ],
#>        [ 0.388,  0.447,  0.191],
#>        [ 0.891,  0.474,  0.212],
#>        [ 0.609,  0.518,  0.403]])
```

In [140]:
rand_arr = np.random.random((5,3))
rand_arr
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.043, 0.88 , 0.763],
       [0.878, 0.418, 0.606],
       [0.513, 0.598, 0.262],
       [0.301, 0.025, 0.303]])

19- Pretty print `rand_arr` by suppressing the scientific notation (like 1e10) 
- Input

```Python
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
```
```Python
rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])
```

- Desired output:
```python
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])
```

In [146]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)#suppress scientific notation
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

20- Limit the number of items printed in python numpy array a to a maximum of 6 elements.
- Input:
```Python
a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```
- Desired output:
```Python
#> array([ 0,  1,  2, ..., 12, 13, 14])
```

In [148]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

21- Convert the 1D iris to 2D array iris_2d by omitting the species text field.
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```
- Desired output:
```Python
#> array([[ 5.1,  3.5,  1.4,  0.2],
#>        [ 4.9,  3. ,  1.4,  0.2],
#>        [ 4.7,  3.2,  1.3,  0.2],
#>        [ 4.6,  3.1,  1.5,  0.2]])
```

In [67]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',')
iris_2d = np.array([row.tolist()[:4] for row in iris_1d]) 
print(iris_2d[:4])
print(iris_2d.shape)
print(iris_1d.shape)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
(150, 4)
(150, 5)


22- Find the mean, median, standard deviation of iris's sepallength (1st column)
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
print(mean, median, sd)
#> 5.84333333333 5.8 0.825301291785
```

In [104]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
print(iris)
sepal= iris[:, [0]]
sepal.astype(float)
print(sepal)
mean=[sum(sepal[i])/len(sepal) for i in sepal]
mean

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Ir

IndexError: arrays used as indices must be of integer (or boolean) type

23- Create a normalized form of iris‘s sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
print(S)
#> [ 0.222  0.167  0.111  0.083  0.194  0.306  0.083  0.194  0.028  0.167
#>   0.306  0.139  0.139  0.     0.417  0.389  0.306  0.222  0.389  0.222
#>   0.306  0.222  0.083  0.222  0.139  0.194  0.194  0.25   0.25   0.111
#>   0.139  0.306  0.25   0.333  0.167  0.194  0.333  0.167  0.028  0.222
#>   0.194  0.056  0.028  0.194  0.222  0.139  0.222  0.083  0.278  0.194
#>   0.75   0.583  0.722  0.333  0.611  0.389  0.556  0.167  0.639  0.25
#>   0.194  0.444  0.472  0.5    0.361  0.667  0.361  0.417  0.528  0.361
#>   0.444  0.5    0.556  0.5    0.583  0.639  0.694  0.667  0.472  0.389
#>   0.333  0.333  0.417  0.472  0.306  0.472  0.667  0.556  0.361  0.333
#>   0.333  0.5    0.417  0.194  0.361  0.389  0.389  0.528  0.222  0.389
#>   0.556  0.417  0.778  0.556  0.611  0.917  0.167  0.833  0.667  0.806
#>   0.611  0.583  0.694  0.389  0.417  0.583  0.611  0.944  0.944  0.472
#>   0.722  0.361  0.944  0.556  0.667  0.806  0.528  0.5    0.583  0.806
#>   0.861  1.     0.583  0.556  0.5    0.944  0.556  0.583  0.472  0.722
#>   0.667  0.722  0.417  0.694  0.667  0.667  0.556  0.611  0.528  0.444]
```

In [106]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepal= iris[:, [0]]
sepal.astype(float)
print(sepal)
sepalmax, sepalmin = sepal.max(), sepal.min()
print(sepalmax,sepalmin)
output = (sepal- sepalmin)/(sepalmax - sepalmin)

[[b'5.1']
 [b'4.9']
 [b'4.7']
 [b'4.6']
 [b'5.0']
 [b'5.4']
 [b'4.6']
 [b'5.0']
 [b'4.4']
 [b'4.9']
 [b'5.4']
 [b'4.8']
 [b'4.8']
 [b'4.3']
 [b'5.8']
 [b'5.7']
 [b'5.4']
 [b'5.1']
 [b'5.7']
 [b'5.1']
 [b'5.4']
 [b'5.1']
 [b'4.6']
 [b'5.1']
 [b'4.8']
 [b'5.0']
 [b'5.0']
 [b'5.2']
 [b'5.2']
 [b'4.7']
 [b'4.8']
 [b'5.4']
 [b'5.2']
 [b'5.5']
 [b'4.9']
 [b'5.0']
 [b'5.5']
 [b'4.9']
 [b'4.4']
 [b'5.1']
 [b'5.0']
 [b'4.5']
 [b'4.4']
 [b'5.0']
 [b'5.1']
 [b'4.8']
 [b'5.1']
 [b'4.6']
 [b'5.3']
 [b'5.0']
 [b'7.0']
 [b'6.4']
 [b'6.9']
 [b'5.5']
 [b'6.5']
 [b'5.7']
 [b'6.3']
 [b'4.9']
 [b'6.6']
 [b'5.2']
 [b'5.0']
 [b'5.9']
 [b'6.0']
 [b'6.1']
 [b'5.6']
 [b'6.7']
 [b'5.6']
 [b'5.8']
 [b'6.2']
 [b'5.6']
 [b'5.9']
 [b'6.1']
 [b'6.3']
 [b'6.1']
 [b'6.4']
 [b'6.6']
 [b'6.8']
 [b'6.7']
 [b'6.0']
 [b'5.7']
 [b'5.5']
 [b'5.5']
 [b'5.8']
 [b'6.0']
 [b'5.4']
 [b'6.0']
 [b'6.7']
 [b'6.3']
 [b'5.6']
 [b'5.5']
 [b'5.5']
 [b'6.1']
 [b'5.8']
 [b'5.0']
 [b'5.6']
 [b'5.7']
 [b'5.7']
 [b'6.2']
 [b'5.1']
 [b'5.7']


TypeError: unsupported operand type(s) for -: 'bytes' and 'bytes'

24- Find the number and position of missing values in iris_2d‘s sepallength (1st column)
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```
- Desired output:
```Python
#> Number of missing values: 
...
#> Position of missing values: 
...
```

In [107]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))


array([[5.1, 3.5, nan, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, nan, nan, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

25- Select the rows of iris_2d that does not have any nan value
- Input:
```Python
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [108]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

26- Replace all ccurrences of `nan` with 0 in numpy array
- Input
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [40]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

27- Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> 'small'
- 3-5 –> 'medium'
- '>=5 –> 'large'
- Input 
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```
- Desired output:
```Python
petal_length_cat[:4]
#> ['small', 'small', 'small', 'small']
```

In [ ]:
# Your code here

28- Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
- Input 
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
#> 50
```

In [43]:
# Your code here

29- From the array a, replace all values greater than 30 to 30 and less than 10 to 10. 
- Input:
```Python
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```
- Desired output:
```Python
#> [ 27.63  14.64  21.8   30.    10.    10.    30.    30.    10.    29.18  30.
#>   11.25  10.08  10.    11.77  30.    30.    10.    30.    14.43]
```

In [111]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

30- Import the image from the following URL and convert it to a numpy array. URL = ‘https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg’
- Input
```Python
from io import BytesIO
from PIL import Image
import PIL, requests
```

In [44]:
from io import BytesIO
from PIL import Image
import PIL, requests

