<h1 align="center">Python performance exercises</h1>

## Python best practices exercises

### Exercise 1

considering the following function for concatenating list strings with deliter.

In [10]:
def ft_concatenate(l_strings, d):
    """concatenate list of strings into one string separated by delimeter"""
    res = l_strings[0]
    for e in l_strings[1:]:
        res = res + d + e
    return res

- profile the function and identify the bottlenecks.
- improve speed up of the function
*Hint: you may need to look to the string functions in python documentation*

In [20]:
L=('The','wolf','of','wall','street')
a=' '
ft_concatenate(L,a)
%timeit ft_concatenate(L,a)
%prun ft_concatenate(L,a)

#speed up the function
def ft_concatenate_spedup(l_strings):
    concatenated_strings = "".join(l_strings)
    return concatenated_strings
%timeit ft_concatenate_spedup(L)
%prun ft_concatenate_spedup(L)
%lprun -f ft_concatenate ft_concatenate(L,a)
%lprun -f ft_concatenate_spedup ft_concatenate_spedup(L)

#thr use of the provided join function decreased considerably the running timer by nearly 1/6th.  the line by line profiling proves that the most time consumming part is the the sum in the first function 

719 ns ± 54.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
 178 ns ± 12 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
 

In [12]:
%time ft_concatenate(L,a)

Wall time: 0 ns


'The wolf of wall street'

### Exercise 2

In this exercise you will solve the following problem using two methods bruteforce mehode, and fast method.

**Problem:** You are given a list of n integers, and your task is to calculate the number of distinct values in the list.

**Example**
- Input:
5
2 3 2 2 3

- Output:
2

**Implement the following methodes:**

1. **bruteforce mehode:** create an empty list and start adding items for the given list without adding the previous item add, at the end the result list will contain unique values, print lenght of the list and you are done. 
2. **fast method** think of using Set data structure.

- time the two methods, what do you think?

In [1]:
# bruteforce fast method
def bruteforce_method(inp):
    bf_list=[]
    for x in inp: 
        if not (x in bf_list):
            bf_list.append(x) 
    return len(bf_list)
inp2=[5,2,3,2,2,3]
bruteforce_method(inp2)

3

In [2]:
# write fast method
an_array = [5,2,3,2,2,3] # repeated values
def fast_method(inp):
    a_set = set(inp) # non-repeated, unique values
    return len(a_set)
fast_method(an_array)

3

In [3]:
# Creat two random lists of numbers for testing
L1=[20,10,25,25,25,26,59,89,48,23,58,58]
L2=[1,2,3,5,5,8,9,4,7,6]
%timeit bruteforce_method(L1)
bruteforce_method(L2)
%timeit fast_method(L1)
fast_method(L2)
# time the two methods
#their is an important decrease nearly 1/3

3.68 µs ± 890 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
968 ns ± 29.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


9

In [12]:
%prun  bruteforce_method(L1)
%prun  fast_method(L1)

## Cython exercises

### Exercise 1

1. load the cython extension.

In [13]:
%load_ext cython

2. Condidering the following polynome function:

In [14]:
def poly(a,b):
    return 10.5 * a + 3 * (b**2)

- Create an equivalent Cython function of `poly` with name `poly_cy` without any cython improvement, just make its cell a cython cell.

In [15]:
%%cython 
def poly_cy(a,b):
    return 10.5 * a + 3 * (b**2)

DistutilsPlatformError: Unable to find vcvarsall.bat

3. time the performance of Python and Cython version of the function, what is the factor of speed up here between the two verions.

In [16]:
%time poly(5,3)
%time poly_cython(5,3)
#No comment as cython is not working for me 

Wall time: 0 ns


NameError: name 'poly_cython' is not defined

### The cell magic compiles the cell into a standalone Cython module, it does not have access to any variable or function defined in the interactive namespace. 

4. Now lets work on another examples using loop.
    - rewrite the same function below fib that calculate fibonacci series using cython, but now try to add type for the variables used inside it, add a prefix `_cy` to your new cython function.

In [17]:
def fib(n):
    a, b = 1, 1
    for i in range(n):
        a, b = a + b, a

    return a

In [19]:
import numpy as np
%%cython
def fib_cy(int  n):
    cdef int a,b
    a, b = 1, 1
    for i in range(n):
        a, b = a + b, a

    return a

SyntaxError: invalid syntax (Temp/ipykernel_12236/288896009.py, line 3)

- time the two function for fibonacci series, with n = 20, what is the factor of speed now, What do you think?

In [16]:
%timeit fib(20)
%timeit fib_cy(20)

5. Recursive functions are functions that call themselves during their execution. Another interesting property of the Fibonacci series is that it can be written as a recursive function. That’s because each item depends on the values of other items (namely item n-1 and item n-2)

- Rewrite the fib function using recursion. Is it faster than the non-recursive version? Does Cythonizing it give even more of an advantage? 

In [ ]:
#generally the Fibonacci sequence starts with a 0 or 1 (debatable), if n= 1 or 0 the functionmust return 0,1 
#if n=2 it will also return 1 (result =(n-2)+(n-1))
def fib_recur(n):
    result=0
    if n==1 : 
        return 1
    elif n==2: 
        return 1
    elif n>2: 
        return fib_recur(n-2)+fib_recur(n-1)
    return result 
fib_recur(20)

In [ ]:
%timeit fib(20)
%timeit fib_recur(20)

### Exercise 2

- Monte Carlo methods are a broad class of computational algorithms that rely on repeated random sampling to obtain numerical results. 
- One of the basic examples of getting started with the Monte Carlo algorithm is the estimation of Pi.

**Estimation of Pi**

- The idea is to simulate random (x, y) points in a 2-D plane with domain as a square of side 1 unit. 
- Imagine a circle inside the same domain with same diameter and inscribed into the square. 
- We then calculate the ratio of number points that lied inside the circle and total number of generated points. 
- Refer to the image below:

![demo](../data/MonteCarloPlot.png)

We know that area of the square is 1 unit sq while that of circle is $\pi \ast  (\frac{1}{2})^{2} = \frac{\pi}{4}$. Now for a very large number of generated points,

![demo](../data/MonteCarloCalc.png)


## The Algorithm

1. Initialize cile_points, square_points and interval to 0.
2. Generate random point x.
3. Generate random point y.
4. Calculate d = x*x + y*y.
5. If d <= 1, increment circle_points.
6. Increment square_points.
7. Increment interval.
8. If increment < NO_OF_ITERATIONS, repeat from 2.
9. Calculate pi = 4*(circle_points/square_points).
10. Terminate.

**Your mission:** time the function `monte_carlo_pi`, identify the bottlenecks and create a new version using cython functionality to speed up monte carlo simulation for PI, use 100,000 points and compare the speed up factor between python and cython, considering the following optimizations:
- add type for variables used.
- add type for the function
- use c rand function instead of python rand function.
 
*Hint: you can import function from C libraries using the following approach `from libc.<name of c library> cimport <library function name>`, replace the holders `<>` with the right identities for the current problem*

In [32]:
import random
def monte_carlo_pi(nsamples):
    pi = 0
    circle_points = 0
    square_points =0 
    #interval= 0 Where are we supposed to use the interval
    for i in range(nsamples) : 
        x= random.uniform(-1,1)
        y=random.uniform(-1,1)
        d=x**2+y**2 #computing the distance from the origin 
        if d<=1: 
            circle_points=circle_points+1
        square_points= square_points+1
    pi = 4*circle_points/square_points
    return pi

In [34]:
monte_carlo_pi(100000)
%time monte_carlo_pi(100000)
%timeit monte_carlo_pi(100000)
%prun monte_carlo_pi(100000)
%lprun monte_carlo_pi(100000)
#The table indicates that the bulk of execution time is in the generation of the random variables x and y (inside the for loop). Therefore, we can assign some changes that might improve the performance of the algorithm.



Wall time: 233 ms
204 ms ± 8.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
 

In [30]:
def monte_carlo_pi_cy(int nsamples):
    cdef float pi, x,y, d
    cdef int circle_points,square_points   
    pi = 0
    circle_points = 0
    square_points =0 
    #interval= 0 Where are we supposed to use the interval
    for i in range(nsamples) : 
        x= random.uniform(-1,1)
        y=random.uniform(-1,1)
        d=x**2+y**2 #computing the distance from the origin 
        if d<=1: 
            circle_points=circle_points+1
        square_points= square_points+1
    pi = 4*circle_points/square_points
    return pi

SyntaxError: invalid syntax (Temp/ipykernel_10120/51553088.py, line 1)

## Numba exercises

### Exercise 1

Previously we considered how to approximateby Monte Carlo.

- Use the same idea here, but make the code efficient using Numba.
- Compare speed with and without Numba when the sample size is large.

In [39]:
import numpy as np
import numba
from numba import jit
import random
@jit(nopython=True)
def monte_carlo_pi_numba(nsamples):
    pi = 0
    circle_points = 0
    square_points =0 
    #interval= 0 Where are we supposed to use the interval
    for i in range(nsamples) : 
        x= random.uniform(-1,1)
        y=random.uniform(-1,1)
        d=x**2+y**2 #computing the distance from the origin 
        if d<=1: 
            circle_points=circle_points+1
        square_points= square_points+1
    pi = 4*circle_points/square_points
    return pi
pi_numba= monte_carlo_pi_numba(10000)
pi_numba


3.1408

In [40]:
%timeit pi_numba 
%timeit monte_carlo_pi(100000)
#the use of Numba made the calclations quicker as it moved from microseconds to nanoseconds

44.3 ns ± 1.56 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
200 ms ± 2.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Exercise 2

In the [Introduction to Quantitative Economics](https://python.quantecon.org/intro.html) with Python lecture series you can learn all about finite-state Markov chains.

For now, let's just concentrate on simulating a very simple example of such a chain.

Suppose that the volatility of returns on an asset can be in one of two regimes — high or low.

The transition probabilities across states are as follows ![markov](../data/markov.png)

For example, let the period length be one day, and suppose the current state is high.

We see from the graph that the state tomorrow will be

- high with probability 0.8

- low with probability 0.2

Your task is to simulate a sequence of daily volatility states according to this rule.

Set the length of the sequence to `n = 1_000_000` and start in the high state.

Implement a pure Python version and a Numba version, and compare speeds.

To test your code, evaluate the fraction of time that the chain spends in the low state.

If your code is correct, it should be about 2/3.

Hints:

- Represent the low state as 0 and the high state as 1.

- If you want to store integers in a NumPy array and then apply JIT compilation, use `x = np.empty(n, dtype=np.int_)`.


In [102]:
def MC_simulation(P, initial_state, sample_size): 
    #set up 
    P= np.asarray()
    X= np.empty(sample_size,dtype=int)
    X[0]=int(initial_state)#we set a default value
    # Convert each row of P into a cdf
    n = len(P)
    P_dist = [np.cumsum(P[i, :]) for i in range(n)] 
    # simulate
    for t in range(sample_size - 1):
        X[t+1] = np.random.choice(P_dist[X[t]])
    return X
M = [[0.8, 0.2],
     [0.1, 0.9]]
X = mc_sample_path(M, 1, 1_000_000)
print(X, np.mean(X == 1))
N = [[0.9, 0.1],
     [0.2, 0.8]]
Y=mc_sample_path(N, 0, 1_000_000)
print(Y, np.mean(Y == 0))

make sure the sum of the Markov matrix rows is equal 1 
[1 1 0 ... 0 1 1] 0.500229
make sure the sum of the Markov matrix rows is equal 1 
[0 1 1 ... 0 1 0] 0.500055


In [108]:
@jit(nopython=True)
def MC_simulation_numba(P, initial_state, sample_size): 
    #set up 
    P= np.asarray()
    X= np.empty(sample_size,dtype=int)
    X[0]=int(initial_state)#we set a default value
    # Convert each row of P into a cdf
    n = len(P)
    P_dist = [np.cumsum(P[i, :]) for i in range(n)] 
    # simulate
    for t in range(sample_size - 1):
        X[t+1] = np.random.choice(P_dist[X[t]])
    return X
M_numba = [[0.8, 0.2],
     [0.1, 0.9]]
X_numba = mc_sample_path(M_numba, 1, 1_000_000)
print(X_numba, np.mean(X_numba == 1))
N_numba = [[0.9, 0.1],
     [0.2, 0.8]]
Y_numba=mc_sample_path(N_numba, 0, 1_000_000)
print(Y_numba, np.mean(Y_numba == 0))

make sure the sum of the Markov matrix rows is equal 1 
[1 1 1 ... 0 0 1] 0.500479
make sure the sum of the Markov matrix rows is equal 1 
[0 1 0 ... 0 0 0] 0.499814


In [112]:
%timeit X 
%timeit X_numba
%lprun X 
%lprun X_numba

44.5 ns ± 4.82 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
45.9 ns ± 6.19 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


## Additionnal exercice

##Type Markdown and LaTeX:  𝛼2

In [104]:
from IPython.display import display, Math, Latex
display(Math(r'a^2'))

<IPython.core.display.Math object>

In [113]:
%%latex
$a^2$

<IPython.core.display.Latex object>