# Exercises for Numpy

1- Import numpy as `np` and print the version number. 

In [1]:
import numpy as np
print(np.__version__)

1.19.4


2- Create a 1D array of numbers from 0 to 9 
- Desired output:
```Python
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [4]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


3- Create a 3×3 numpy array of all True’s
- Desired output:
```Python
#> array([[ True,  True,  True],
#>        [ True,  True,  True],
#>        [ True,  True,  True]], dtype=bool)
```

In [28]:
b = np.ones((3, 3), dtype=np.bool)
print(b)

[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


4- Extract all odd numbers from `arr` 
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#> array([1, 3, 5, 7, 9])
```

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 != 0])

[1 3 5 7 9]


5- Replace all odd numbers in arr with -1
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [8]:
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6- Replace all odd numbers in arr with -1 without changing `arr` 
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [29]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 == 1, -1, arr)
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


7- Convert a 1D array to a 2D array with 2 rows
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [22]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
n_arr = arr.reshape((2, -1))
print(n_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


8- Stack arrays `a` and `b` vertically 
- Input
```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [32]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Method 1:
meth1 = np.concatenate([a, b], axis=0)

# Method 2:
meth2 = np.vstack([a, b])

# Method 3:
meth3 = np.r_[a, b]

print(meth1)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]



9- Stack the arrays a and b horizontally.
- Input
```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [33]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10- Get the common items between `a` and `b` 
- Input
```Python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
- Desired output:
```Python
#> array([2, 4])
```

In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

11- From array `a` remove all items present in array `b` 
- Input
```Python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
- Desired output:
```Python
#> array([1,2,3,4])
```

In [35]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a, b)

array([1, 2, 3, 4])

12- Get the positions where elements of `a` and `b` match
- Input
```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```
- Desired output:
```Python
#> (array([1, 3, 5, 7]),)
```

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

13- Get all items between 5 and 10 from `a`
- Input
```Python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```
- Desired output:
```Python
#> (array([6, 9, 10]),)
```

In [39]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

14- Convert the function `maxx` that works on two scalars, to work on two arrays
- Input
```Python
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
```
```Python
maxx(1, 5)
#> 5
```

- Desired output:

```Python
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [40]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

array([6., 7., 9., 8., 9., 7., 5.])

15- Reverse the rows of a 2D array `arr`
- Input
```Python
arr = np.arange(9).reshape(3,3)
```
- Desired output:
```Python
#> array([[6, 7, 8],
#>       [3, 4, 5],
#>       [0, 1, 2]])
```

In [43]:
arr = np.arange(9).reshape(3,3)

arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

16- Reverse the columns of a 2D array `arr`
- Input
```Python
arr = np.arange(9).reshape(3,3)
```
- Desired output:
```Python
#> array([[2, 1, 0],
#>        [5, 4, 3],
#>        [8, 7, 6]])
```

In [45]:
arr = np.arange(9).reshape(3,3)

arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

17- Create a 2D array of shape 5×3 to contain random decimal numbers between 5 and 10 (use `np.random.seed()` to generate the same random output).
- Desired output: (for seed number equal 10)
```Python
#> array([[6.15037787, 9.68381843, 5.81660184],
#>       [6.33607158, 8.89081653, 9.19812181],
#>       [6.03061665, 5.87761494, 6.72743551],
#>       [7.54088093, 5.13145815, 6.41366737],
#>       [5.77872881, 7.58390137, 5.18263144]])
```

In [98]:
np.random.seed(10)

rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[8.857 5.104 8.168]
 [8.744 7.493 6.124]
 [5.99  8.803 5.846]
 [5.442 8.427 9.767]
 [5.02  7.561 9.063]]


18- Print or show only 3 decimal places of the numpy array `rand_arr`
- Input
```Python
rand_arr = np.random.random((5,3))
```
- Desired output:
```Python
rand_arr[:4]
#> array([[ 0.443,  0.109,  0.97 ],
#>        [ 0.388,  0.447,  0.191],
#>        [ 0.891,  0.474,  0.212],
#>        [ 0.609,  0.518,  0.403]])
```

In [74]:
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.321, 0.208, 0.451],
       [0.492, 0.899, 0.729],
       [0.77 , 0.375, 0.344],
       [0.655, 0.711, 0.114]])

19- Pretty print `rand_arr` by suppressing the scientific notation (like 1e10) 
- Input

```Python
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
```
```Python
rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])
```

- Desired output:
```python
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])
```

In [68]:
np.set_printoptions(suppress=True, precision=6)

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

20- Limit the number of items printed in python numpy array a to a maximum of 6 elements.
- Input:
```Python
a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```
- Desired output:
```Python
#> array([ 0,  1,  2, ..., 12, 13, 14])
```

In [63]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

21- Convert the 1D iris to 2D array iris_2d by omitting the species text field.
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```
- Desired output:
```Python
#> array([[ 5.1,  3.5,  1.4,  0.2],
#>        [ 4.9,  3. ,  1.4,  0.2],
#>        [ 4.7,  3.2,  1.3,  0.2],
#>        [ 4.6,  3.1,  1.5,  0.2]])
```

In [62]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# Solution:
# Method 1: Convert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

# Alt Method 2: Import only the first 4 columns from source url
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

/tmp/ipykernel_835/1000344196.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

22- Find the mean, median, standard deviation of iris's sepallength (1st column)
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
print(mean, median, sd)
#> 5.84333333333 5.8 0.825301291785
```

In [61]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


23- Create a normalized form of iris‘s sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
print(S)
#> [ 0.222  0.167  0.111  0.083  0.194  0.306  0.083  0.194  0.028  0.167
#>   0.306  0.139  0.139  0.     0.417  0.389  0.306  0.222  0.389  0.222
#>   0.306  0.222  0.083  0.222  0.139  0.194  0.194  0.25   0.25   0.111
#>   0.139  0.306  0.25   0.333  0.167  0.194  0.333  0.167  0.028  0.222
#>   0.194  0.056  0.028  0.194  0.222  0.139  0.222  0.083  0.278  0.194
#>   0.75   0.583  0.722  0.333  0.611  0.389  0.556  0.167  0.639  0.25
#>   0.194  0.444  0.472  0.5    0.361  0.667  0.361  0.417  0.528  0.361
#>   0.444  0.5    0.556  0.5    0.583  0.639  0.694  0.667  0.472  0.389
#>   0.333  0.333  0.417  0.472  0.306  0.472  0.667  0.556  0.361  0.333
#>   0.333  0.5    0.417  0.194  0.361  0.389  0.389  0.528  0.222  0.389
#>   0.556  0.417  0.778  0.556  0.611  0.917  0.167  0.833  0.667  0.806
#>   0.611  0.583  0.694  0.389  0.417  0.583  0.611  0.944  0.944  0.472
#>   0.722  0.361  0.944  0.556  0.667  0.806  0.528  0.5    0.583  0.806
#>   0.861  1.     0.583  0.556  0.5    0.944  0.556  0.583  0.472  0.722
#>   0.667  0.722  0.417  0.694  0.667  0.667  0.556  0.611  0.528  0.444]
```

In [60]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
# or 
S = (sepallength - Smin)/sepallength.ptp()  # Thanks, David Ojeda!
print(S)

[0.22 0.17 0.11 0.08 0.19 0.31 0.08 0.19 0.03 0.17 0.31 0.14 0.14 0.
 0.42 0.39 0.31 0.22 0.39 0.22 0.31 0.22 0.08 0.22 0.14 0.19 0.19 0.25
 0.25 0.11 0.14 0.31 0.25 0.33 0.17 0.19 0.33 0.17 0.03 0.22 0.19 0.06
 0.03 0.19 0.22 0.14 0.22 0.08 0.28 0.19 0.75 0.58 0.72 0.33 0.61 0.39
 0.56 0.17 0.64 0.25 0.19 0.44 0.47 0.5  0.36 0.67 0.36 0.42 0.53 0.36
 0.44 0.5  0.56 0.5  0.58 0.64 0.69 0.67 0.47 0.39 0.33 0.33 0.42 0.47
 0.31 0.47 0.67 0.56 0.36 0.33 0.33 0.5  0.42 0.19 0.36 0.39 0.39 0.53
 0.22 0.39 0.56 0.42 0.78 0.56 0.61 0.92 0.17 0.83 0.67 0.81 0.61 0.58
 0.69 0.39 0.42 0.58 0.61 0.94 0.94 0.47 0.72 0.36 0.94 0.56 0.67 0.81
 0.53 0.5  0.58 0.81 0.86 1.   0.58 0.56 0.5  0.94 0.56 0.58 0.47 0.72
 0.67 0.72 0.42 0.69 0.67 0.67 0.56 0.61 0.53 0.44]


24- Find the number and position of missing values in iris_2d‘s sepallength (1st column)
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```
- Desired output:
```Python
#> Number of missing values: 
...
#> Position of missing values: 
...
```

In [58]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 8
Position of missing values: 
 (array([ 12,  17,  20,  45, 102, 107, 109, 116]),)


25- Select the rows of iris_2d that does not have any nan value
- Input:
```Python
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [57]:
# Method 1:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

# Method 2: (By Rong)
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[5.1, 0. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

26- Replace all ccurrences of `nan` with 0 in numpy array
- Input
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[5.1, 0. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

27- Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> 'small'
- 3-5 –> 'medium'
- '>=5 –> 'large'
- Input 
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```
- Desired output:
```Python
petal_length_cat[:4]
#> ['small', 'small', 'small', 'small']
```

In [54]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]

['small', 'small', 'small', 'small']

28- Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
- Input 
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
#> 50
```

In [53]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50])

29- From the array a, replace all values greater than 30 to 30 and less than 10 to 10. 
- Input:
```Python
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```
- Desired output:
```Python
#> [ 27.63  14.64  21.8   30.    10.    10.    30.    30.    10.    29.18  30.
#>   11.25  10.08  10.    11.77  30.    30.    10.    30.    14.43]
```

In [46]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution 1: Using np.clip
np.clip(a, a_min=10, a_max=30)

# Solution 2: Using np.where
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.63 14.64 21.8  30.   10.   10.   30.   30.   10.   29.18 30.   11.25
 10.08 10.   11.77 30.   30.   10.   30.   14.43]


30- Import the image from the following URL and convert it to a numpy array. URL = ‘https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg’
- Input
```Python
from io import BytesIO
from PIL import Image
import PIL, requests
```

In [52]:
from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([150,150])

# Convert to numpy array
arr = np.asarray(I)

# Optionaly Convert it back to an image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

display-im6.q16: unable to open X server `' @ error/display.c/DisplayImageCommand/432.
